### ISSUE TITLE
Crash when using PassthroughEnv

### ISSUE THREAD

**Issue by drhagen** [cjolowicz/nox-poetry#347]
Starting in v0.8.2, using `@nox_poetry.session(venv_backend='none')` causes a crash. This was introduced in #298 and is caused by accessing the nonexistant `location` attribute of the `PassthroughEnv` object in `_PoetrySession.export_requirements`.

Example script:

```
import nox_poetry

@nox_poetry.session(venv_backend='none')
def lint(session: nox_poetry.Session):
    session.install('flakehell', 'flake8', 'pep8-naming', 'flake8-quotes')
    session.run('flakehell', 'lint', 'src', 'tests', 'examples')
```

Example error message:

```
nox > Running session lint
nox > Session lint raised exception AttributeError("'PassthroughEnv' object has no attribute 'location'")
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/site-packages/nox/sessions.py", line 549, in execute
    self.func(session)
  File "/opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/site-packages/nox/_decorators.py", line 53, in __call__
    return self.func(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/site-packages/nox_poetry/sessions.py", line 42, in wrapper
    function(proxy, *_args, **_kwargs)
  File "/home/runner/work/parsita/parsita/noxfile.py", line 22, in lint
    session.install('flakehell', 'flake8', 'pep8-naming', 'flake8-quotes')
  File "/opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/site-packages/nox_poetry/sessions.py", line 276, in install
    return self.poetry.install(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/site-packages/nox_poetry/sessions.py", line 144, in install
    requirements = self.export_requirements()
  File "/opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/site-packages/nox_poetry/sessions.py", line 200, in export_requirements
    tmpdir = Path(self.session.virtualenv.location) / "tmp"
AttributeError: 'PassthroughEnv' object has no attribute 'location'
```

**Comment by cjolowicz** [comment]
Thank you for catching this!

The idea in #298 was to, essentially, do what `session.create_tmp` does but without setting `TMPDIR`. Instead of `session._runner.envdir` we're using `session.virtualenv.location` because it's a public API. It was an oversight that this does not work for `PassthoughEnv`.

The fix would be here:

https://github.com/cjolowicz/nox-poetry/blob/1afc0a007cea88614ff1e0b8be1415e0f8e84253/src/nox_poetry/sessions.py#L200-L201

I'd be fine with switching to the private API, and passing `parents=True` to ensure the directory can be created. This would be emulating `session.create_tmp`.

There have also been thoughts about using just a [single requirements file for all sessions](https://github.com/cjolowicz/nox-poetry/issues/249#issuecomment-798363550). I think we don't need per-session requirements files anymore.

**Comment by cjolowicz** [comment]
Fix released in 0.8.5, could you give it a spin?

**Comment by drhagen** [comment]
I have [confirmed](https://github.com/drhagen/parsita/runs/2467199782) that this is fixed.

**Comment by cjolowicz** [comment]
Thank you!
